### ISSUE TITLE
Plugin incompatibilities due to server-side itemstack modifications

### ISSUE THREAD

**Issue by blablubbabc** [Warren1001/attributehider#7]
A user of one of my plugins (Shopkeepers) ran into issues with trading. The Shopkeepers plugin uses the villager trading interface to display trades and handle trade interactions.

In some cases, this plugin (AttributeHider) seems to modify items on the server (e.g. it adds the `HideFlags` tag). This can cause issue in combination with shop plugins like Shopkeepers, which compare the NBT data of items to make sure that the item provided by a player matches the item required by the trade.

According to your changelog (https://www.spigotmc.org/resources/attributehider.10604/update?update=345929), you attempted to resolve these kinds of issues in the past by only visually modifying the items in outgoing packets. However, it seems that in some cases, you still modify the items on the server.

For example, when you handle the WINDOW_ITEMS packet (https://github.com/Warren1001/attributehider/blob/master/src/main/java/com/kabryxis/attributehider/remover/RemoverPacketListener.java#L38), ProtocolLib may return you a list of CraftItemStacks. Any modifications you do to these ItemStacks write through to the underlying Minecraft ItemStacks inside the inventory on the server.
The solution might be to ensure that you always copy the itemstacks of the outgoing packets before you modify them.

Looking at the ProtocolLib and CraftBukkit implementations, in some cases ProtocolLib might already automatically copy the item stacks for you (although this is unspecified): For example, for the list of MerchantRecipes that you get from ProtocolLib when you handle the OPEN_WINDOW_MERCHANT packet (https://github.com/Warren1001/attributehider/blob/master/src/main/java/com/kabryxis/attributehider/remover/RemoverPacketListener.java#L46), ProtocolLib invokes nms.MerchantRecipe#asBukkit (https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/BukkitConverters.java#L1570), which creates copies of the items of the underlying Minecraft merchant recipes (see CraftBukkit implementation).

However, in other cases, such as whenever you retrieve ItemStacks via ProtocolLib's ItemStack converter, ProtocolLib may return you the mentioned CraftItemStack wrappers instead of copies. So you may need to manually copy the items in those cases yourself before you modify them.

Edit: You can confirm this yourself by getting yourself some tool item (e.g. a sword), open and close your inventory (to ensure your packet listener is invoked), and then check the NBT of the sword item inside your inventory via Minecraft's `/data get entity @s` command. You will notice that the item now contains the `HideFlags` tag.

**Comment by Warren1001** [comment]
i had wondered if that would be the case, but hadnt seen any issues yet. ty
for the heads up, ill look into it and see what the best course of action is
